### ISSUE TITLE
SCPI.py ResourceManager error

### ISSUE THREAD

**Issue by Nickellick** [sgoadhouse/msox3000#3]
When I try to open instance of oscillosocpe, I recieve an error:
```py
Traceback (most recent call last):
  File "C:\Users\nickellick\PycharmProjects\dsox3104T_control\rest2.py", line 7, in <module>
    inst.open()
  File "C:\Users\nickellick\PycharmProjects\dsox3104T_control\venv\lib\site-packages\msox3000\SCPI.py", line 79, in open
    self._inst = self._rm.open_resource(self._resource,
  File "C:\Users\nickellick\PycharmProjects\dsox3104T_control\venv\lib\site-packages\pyvisa\highlevel.py", line 3304, in open_resource
    res.open(access_mode, open_timeout)
  File "C:\Users\nickellick\PycharmProjects\dsox3104T_control\venv\lib\site-packages\pyvisa\resources\resource.py", line 297, in open
    self.session, status = self._resource_manager.open_bare_resource(
  File "C:\Users\nickellick\PycharmProjects\dsox3104T_control\venv\lib\site-packages\pyvisa\highlevel.py", line 3232, in open_bare_resource
    return self.visalib.open(self.session, resource_name, access_mode, open_timeout)
  File "C:\Users\nickellick\PycharmProjects\dsox3104T_control\venv\lib\site-packages\pyvisa_py\highlevel.py", line 167, in open
    sess = cls(session, resource_name, parsed, open_timeout)
  File "C:\Users\nickellick\PycharmProjects\dsox3104T_control\venv\lib\site-packages\pyvisa_py\sessions.py", line 266, in __init__
    raise ValueError(msg)
ValueError: PyUSB does not seem to be properly installed.
Please refer to PyUSB documentation and 
install a suitable backend like 
libusb 0.1, libusb 1.0, libusbx, 
libusb-win32 or OpenUSB.
No backend available
```
When I fix line #78 at SCPI.py to
```py
self._rm = visa.ResourceManager()
```
It works like a charm. What can it be?

My code is actually pretty simple
```py
from msox3000 import MSOX3000
import pyvisa

rm = pyvisa.ResourceManager()

inst = MSOX3000(rm.list_resources()[0])
inst.open()
inst.hardcopy('test2.png')
```

**Comment by sgoadhouse** [comment]
Somehow I missed this posting until I stumbled upon it so sorry for the delay in addressing it. 

The `'@py'` in line #78 of SCPI.py selects the `pyvisa-py` backend instead of the National Instruments VISA library. My guess from the error message you posted and your results, you must not have pyvisa-py installed, as suggested in the `README.md` but you must have the VISA library installed for it to work. If you prefer to use the VISA library instead, that should work fine. However, my personal experience with the VISA library is that it has caused me many hours debugging and fixing my computer because of how badly it was written. Also, it was installing itself as a kernel module where badly written code can cause bad results. Hopefully the VISA library is better now but since `pyvisa-py` works so well, at least for me, I prefer to use that solution. It does take some effort to get libusb installed correctly but I am making use of libusb in other projects so I have it anyway.

For more information on `pyvisa-py` and how to get it installed, see https://pyvisa-py.readthedocs.io/en/latest/# Otherwise just remove `'@py'` from SCPI.py.

**Comment by Nickellick** [comment]
Thank you! I guess I should try `pyvisa-py` as backend
My oscilloscope freezes when i try to get any data from it. This happens even if I try to use "raw" query in pyvisa, so I hope this is a bug in the NI Visa library.

Thanks again!

**Comment by sgoadhouse** [comment]
Which model do you have? I have the MSO-X 3034A running v2.50 firmware. I find that getting a screen shot via hardcopy() sometimes fails and I have had to resort in those times to using pycurl to grab it from the built-in web server on the oscilloscope. I created a python script named `from_web.py` that is in the repo. When and why hardcopy() fails seems to do with a bug in the oscilloscope because the python code works sometimes fine and sometimes not. 

If you are talking about getting Waveform data, I just yesterday ran into an issue where the oscilloscope locked up with a rotating icon on the screen. It refused to do anything. Button presses where ignored. I had to power cycle to get it working again. If that is what you have run into, then you may still see it with py-visa. Because of the oddities with hardcopy, I expect this is also an issue with MSO-X firmware. I see that there is now a v2.65 firmware available. I have not tried upgrading yet but plan to do so.

Also, we recently got a newer MXR series oscilloscope and so I have expanded the repo into oscope-scpi: https://github.com/sgoadhouse/oscope-scpi This still supports our MSO-X 3034A plus adds support for MXR, EXR and UXR. I tried to make it so that support for Tektronix and Rigol and other scopes can be added in the future by people who have access to those scopes. I did change how getting Waveform data works so you can give that a try as well. I do not yet have it in PyPi but hope to get it finalized enough to go into PyPi within a few days. So if you want to try this, clone the GIT and use `python setup.py install` in the top-level folder of the repo.
